{% set name = "guppy3" %}
{% set version = "3.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/guppy3-{{ version }}.tar.gz
  sha256: 97fbe606a23f837ad109d122bf30fba355785add2dcb68e9a6be335846dd4c48

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - guppy
    - guppy.etc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zhuyifei1999/guppy3/
  summary: Guppy 3 -- Guppy-PE ported to Python 3
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fgypas
